### ISSUE TITLE
시스템 오타

### ISSUE THREAD

**Issue by whffkandy07** [ToyEngine/ToyEngine#10]
https://github.com/ToyEngine/ToyEngine/blob/f49e0684766794e7f07137a18ce10f20a6b05719/Engine/Source/ResourceSystem.h#L67

**Comment by ChoiJiOne** [comment]
2.0 버전에 수정되었습니다.
https://github.com/ToyEngine/ToyEngine/blob/2.0/Engine/Source/ContentManager.h#L131
