### ISSUE TITLE
텍스처 파일? 오타

### ISSUE THREAD

**Issue by whffkandy07** [ToyEngine/ToyEngine#9]
https://github.com/ToyEngine/ToyEngine/blob/f49e0684766794e7f07137a18ce10f20a6b05719/Engine/Source/ResourceSystem.h#L40

**Comment by ChoiJiOne** [comment]
2.0 에서 ResourceSystem을 ContentManager로 수정하면서 변경되었습니다.
https://github.com/ToyEngine/ToyEngine/blob/2.0/Engine/Source/ContentManager.h
